# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_company_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerToCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('NS', 'Not Specified'), ('WI', 'Well-Informed'), ('AO', 'Annoyed One'), ('S', 'Suspicious One'), ('Q', 'Questioner'), ('OWAOE', 'Ones Who Agree On Everything'), ('I', 'Indecisive')], default='NS', max_length=5)),
                ('date_added', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='customers',
            field=models.ManyToManyField(related_name='customers', through='companies.CustomerToCompany', to=settings.AUTH_USER_MODEL),
        ),
    ]
